image: Visual Studio 2017
clone_folder: C:\azalea
platform: x86
configuration: Debug

build_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_PREFIX_PATH="C:\Qt\5.13.0\msvc2017\lib\cmake" -G"NMake Makefiles"
    - nmake
