version: unstable-{build}

image: Visual Studio 2017
clone_folder: C:\azalea
platform: x86
configuration: Debug

build_script:
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86'
    - mkdir release
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_PREFIX_PATH="C:\Qt\5.13.0\msvc2017\lib\cmake" -G"NMake Makefiles" -DCMAKE_INSTALL_PREFIX="C:\azalea\release" -DCMAKE_BUILD_TYPE="Release"
    - nmake
    - nmake install
    - 'copy "C:\OpenSSL-v111-Win32\bin\lib*.dll" "C:\azalea\release"'

artifacts:
   - path: release
     name: release

deploy:
    - provider: GitHub
      artifact: /^release/
      prerelease: true
      repository: unstabler/Azalea
      auth_token:
          secure: aYT8TQoY5LREybjze6yoozyrNvfPH24wHH96tLnuFD6bLUazqG8S3Kdego0r3mBh
      on:
          branch: master
          APPVEYOR_REPO_TAG: true

