version: 2
jobs:
  build:
    docker:
      - image: unstabler/azalea-builder:latest

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: build
          command: |
              mkdir build && cd build
              cmake ..
              make -j4
    
      - run:
          name: run tests
          command: cd build && make test
