name: build on macOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install requirements
      run: brew install openssl qt cmake
    - name: run build
      run: |
        mkdir build
        mkdir release
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt/lib/cmake -DCMAKE_INSTALL_PREFIX=../release
        make -j4
        make install
        cd ../release
        zip -r azalea-bin-macos.zip Azalea.app
    - name: upload releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd release
        curl -Ls https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447/raw/dbadd7d310ce8446de89c4ffdf1db0b400d0f6c3/upload-github-release-asset.sh | bash -s \
          github_api_token=$GITHUB_TOKEN \
          owner=unstabler \
          repo=Azalea \
          tag='testrel-20190929-XXX' \
          filename=azalea-bin-macos.zip


